version: '3.8'

services:
  app:
    build: .
    container_name: sb-api-container
    ports:
      - "3306:3306"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: x1x1x1x
      DB_NAME: registraties
