swagger: "2.0"
info:
  description: "API voor de slagboomapplicatie"
  title: "Slagboomapplicatie API"
  version: "1"
host: "localhost:8080"
basePath: "/"
schemes:
- "http"
paths:
  /check:
    get:
      tags:
      - "Kenteken"
      summary: "Check of een kenteken toegang heeft tot de parkeerplaats"
      description: "Check of een kenteken toegang heeft tot de parkeerplaats"
      produces:
      - "application/json"
      parameters:
      - name: "licenseplate"
        in: "query"
        required: true
        type: "string"
        description: "Kenteken"
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
              status:
                type: "string"
              kenteken:
                type: "string"
              voornaam:
                type: "string"
              achternaam:
                type: "string"
              telefoonnummer:
                type: "string"
        400:
          description: "Bad Request"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
        500:
          description: "Internal Server Error"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
