name: CI/CD for Golang App

on:
  push:
    branches:
      - main  # Voer uit bij elke push naar de main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t slagboom-api .

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: slagboomapplicatieregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push Docker image to Azure Container Registry
      run: |
        docker tag slagboomapplicatie-api slagboomapplicatieregistry.azurecr.io/my-golang-app:latest
        docker push slagboomapplicatieregistry.azurecr.io/my-golang-app:latest

    - name: Deploy to Azure Container Apps (ACI)
      run: az container create --resource-group opslag-rg --name slagboom-api-container --image slagboomapplicatieregistry.azurecr.io/my-golang-app:latest --cpu 1 --memory 1 --ports 8080
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
